// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var file, urlVars;
    urlVars = getUrlVars();
    if (!(urlVars["path"] != null)) {
      urlVars["path"] = "";
    }
    if (!(urlVars["suffix"] != null)) {
      urlVars["suffix"] = "genes";
    }
    if (urlVars["file"]) {
      file = urlVars["path"] + urlVars["file"];
      return d3.text(file, function(text) {
        var parsedFile, volcanoModel, volcanoView;
        parsedFile = d3.csv.parse(text);
        volcanoModel = new window.VolcanoModel(parsedFile);
        volcanoModel.set({
          suffix: urlVars["suffix"]
        });
        return volcanoView = new window.VolcanoView({
          el: "#volcano",
          model: volcanoModel
        });
      });
    } else {
      return $('body').text("Please provide an input file");
    }
  });

}).call(this);
